import './style.scss';
import actions from './js/Components/Actions';
import addForm from './js/Components/AddForm';
import app from './js/App';
import auth from './js/Utilities/Auth';
import editForm from './js/Components/EditForm';
import forgotPassword from './js/Pages/Auth/ForgotPassword';
import indexTable from './js/Components/IndexTable';
import login from './js/Pages/Auth/Login';
import metaTitle from './js/MetaTitle';
import modal from './js/Components/Modal';
import myForm from './js/Components/MyForm';
import nav from './js/Nav';
import resetPassword from './js/Pages/Auth/ResetPassword';

export const Actions = actions;
export const AddForm = addForm;
export const App = app;
export const Auth = auth;
export const EditForm = editForm;
export const ForgotPassword = forgotPassword;
export const IndexTable = indexTable;
export const Login = login;
export const MetaTitle = metaTitle;
export const MyForm = myForm;
export const Modal = modal;
export const Nav = nav;
export const ResetPassword = resetPassword;
